### ISSUE TITLE
Step 4

### ISSUE THREAD

**Issue by Luckick** [acs14007/easy_wrf#1]
Hi Aaron,

I have questions in Step 4.
I did not find the configure.wrf so I created one and fill it with the "COMPRESSION_LIBS ..." as you listed. 
What do you mean "Make sure to set the WRF_DIR variable."? How can I set it? 

I get error in the wrf compile process: 

```
make[2]: Entering directory '/home/stormapp/WRF-4.2.2/frame'
make[2]: *** No rule to make target 'externals'.  Stop.
make[2]: Leaving directory '/home/stormapp/WRF-4.2.2/frame'
make[1]: [Makefile:969: ext] Error 2 (ignored)

DIWORDSIZE= -DMAX_HISTORY=   -c -g  registry.c
/bin/sh: -DMAX_HISTORY=: command not found
make[2]: [Makefile:21: registry.o] Error 127 (ignored)
DIWORDSIZE= -DMAX_HISTORY=   -c -g  my_strtok.c
/bin/sh: -DMAX_HISTORY=: command not found

...

make[1]: *** No rule to make target '../main/module_wrf_top.o', needed by 'wrf.o'.  Stop.
make[1]: Leaving directory '/home/stormapp/WRF-4.2.2/main'
make: *** [Makefile:119: wrf] Error 2
```

Could you please give me some hints? Thank you very much!

Best,
Qinqing

**Comment by acs14007** [comment]
Hi Qinqing!

The configure.wrf file should be created after you run configure! Then you should be able to go in and manually edit the flags before compilation!

Do you want to meet or chat tomorrow about this?

**Comment by acs14007** [comment]
Hi Qinqing.

I just looked into this further. It looks like this occurs if the compile step fails. You can check this if you go to the WRF directory and try to compile wrf. (Option 34 and 1 if you run `./configure`) You will see warnings or errors if there are problems!

If you see netcdf problems you can try compiling in netcdf basic mode where we disable compression features. You can do this by setting the `NETCDF_classic` variable to 1.

**Comment by acs14007** [comment]
I just added that command to the README. That should fix this issue! Please let me know if you run into any other issues!

**Comment by Luckick** [comment]
Thanks for the quick reply! 
I add the export line and we can have a configure.wrf file after ./configure step. And the compile is in the process.

How about the "WRF_DIR", where should we define and which folder should we set?

**Comment by acs14007** [comment]
Yes, so we need to set that up to point to the location of your WRF install. For mine I used `export WRF_DIR=/shared/stormcenter/Aaron/operational_updated_version/aarons_wrf/WRF-4.2.2/`

I can update the instructions so it is more clear!

**Comment by acs14007** [comment]
I just updated the instructions in that step so it is more clear!

Feel free to submit pull requests with any updates as well! I can also add you as an admin if you'd like!
